service: albert-c5-serverless-ii
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  api:
    handler: index.handlerTwo
    events:
      - httpApi:
          path: /albert_get
          method: get
      - sqs:
          arn: arn:aws:sqs:us-east-1:255945442255:albert-serverless-sqs

  postApi:
    handler: index.postHandlerTwo
    events:
      - httpApi:
          path: /albert_post
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - AlbertQueue
              - Arn


resources:
  Resources:
    AlbertQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "albert-queue"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001