service: albert-c5-serverless-ii
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handlerTwo
    events:
      - httpApi:
          path: /albert_get
          method: get
  postApi:
    handler: index.postHandlerTwo
    events:
      - httpApi:
          path: /albert_post
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001